---
title: کاوبوش
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    permalink: authors/:title/
    layout: default
    twitter: 
email: KauBosh@gmail.com
description: شیفته ی شیفتگی
paginate: 5
markdown: kramdown
highlighter: rouge
permalink: none
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
author: کاوبوش
include:
- _pages
- _authors
